package com.mgboard.keyboard.model

/* ============================================================================
 *  SettingsModel.kt  —  GENERATED FILE, DO NOT EDIT BY HAND
 *
 *  Source of truth : Mgboard_Web/index.html  (SG_PAGES / SG_BOOL_DEFAULTS /
 *                    SG_ITEMS + SG_HELP_ITEMS + SG_ABOUT_ITEMS)
 *  Generator       : Mgboard/scripts/gen_settings_model.py
 *  Verify          : python3 Mgboard/scripts/check_parity.py
 *
 *  Web aur Android ka settings model byte-level identical rakha gaya hai:
 *  same page ids, same item ids/order, same EN+HI labels, same summaries,
 *  same search keywords, same Gboard defaults, same gate reason strings.
 * ========================================================================== */

enum class SgType { TOGGLE, SLIDER, ACTION, GATED, INFO }

/** One settings page (Gboard ki 13 + MgBoard ka Developer/Debug). */
data class SgPage(
    val id: String,
    val en: String,
    val hi: String,
    val icon: String,
)

/**
 * One settings row.
 *
 * @param key      SharedPreferences key for a plain boolean toggle (null = custom get/set).
 * @param btn      Static label for ACTION rows (button text).
 * @param gate     Verbatim Gboard reason string shown when a GATED row is tapped.
 * @param min/max/step  SLIDER range (Gboard-exact).
 * @param webFn    The original web get/set/run/dynamic body, kept as a comment-grade
 *                 reference so the Android handler stays faithful to web behaviour.
 */
data class SgItem(
    val id: String,
    val page: String,
    val type: SgType,
    val en: String,
    val hi: String,
    val sumEn: String? = null,
    val sumHi: String? = null,
    val kw: List<String> = emptyList(),
    val key: String? = null,
    val btn: String? = null,
    val gate: String? = null,
    val min: Double = 0.0,
    val max: Double = 1.0,
    val step: Double = 1.0,
    val webFn: String? = null,
)

object SgPages {
    val ALL: List<SgPage> = listOf(
        SgPage("preferences", "Preferences", "प्राथमिकताएं", "settings"),
        SgPage("theme", "Theme", "थीम", "theme"),
        SgPage("languages", "Languages", "भाषाएं", "imeSwitch"),
        SgPage("glide", "Glide typing", "ग्लाइड करके टाइप करना", "glide"),
        SgPage("correction", "Text correction", "टेक्स्ट सुधार", "check"),
        SgPage("voice", "Voice typing", "बोली को लिखाई में बदलना", "voice"),
        SgPage("expressions", "Emojis, Stickers & GIFs", "इमोजी, स्टिकर और GIF", "emoji"),
        SgPage("clipboard", "Clipboard", "क्लिपबोर्ड", "clipboard"),
        SgPage("personalization", "Personalization", "पर्सनलाइज़ेशन", "person"),
        SgPage("privacy", "Privacy", "निजता", "lock"),
        SgPage("advanced", "Advanced", "उन्नत", "wrench"),
        SgPage("debug", "Developer / Debug", "डेवलपर / डीबग", "flask"),
        SgPage("help", "Help & feedback", "सहायता और फ़ीडबैक", "help"),
        SgPage("about", "About", "जानकारी", "info"),
    )

    fun byId(id: String): SgPage? = ALL.firstOrNull { it.id == id }
}

object SgDefaults {
    /** Gboard-exact boolean defaults — web ke SG_BOOL_DEFAULTS se identical. */
    val BOOL: Map<String, Boolean> = mapOf(
        "sg_adapt" to true,
        "sg_auto_cap" to true,
        "sg_auto_correct" to true,
        "sg_auto_space" to true,
        "sg_battery_saver_theme" to false,
        "sg_context" to true,
        "sg_conv_history" to false,
        "sg_cp_enabled" to true,
        "sg_cp_screenshots" to false,
        "sg_cp_suggestions" to true,
        "sg_double_space_period" to true,
        "sg_emoji_kitchen" to true,
        "sg_emoji_row" to true,
        "sg_emoji_suggestions" to true,
        "sg_glide" to true,
        "sg_glide_cursor" to true,
        "sg_glide_delete" to true,
        "sg_glide_trail" to false,
        "sg_glide_word" to true,
        "sg_grammar" to false,
        "sg_incognito" to false,
        "sg_inline" to false,
        "sg_key_borders" to false,
        "sg_minimize_toolbar" to false,
        "sg_next_word" to true,
        "sg_number_row" to false,
        "sg_pd_enabled" to true,
        "sg_popup" to true,
        "sg_screen_context" to false,
        "sg_show_emoji_key" to true,
        "sg_show_lang_key" to false,
        "sg_smart_compose" to false,
        "sg_sound" to false,
        "sg_stats" to false,
        "sg_sticker_suggestions" to false,
        "sg_suggestion_strip" to true,
        "sg_toolbar" to true,
        "sg_vibrate" to true,
        "sg_voice_auto_punct" to true,
        "sg_voice_auto_start" to false,
        "sg_voice_commands" to true,
        "sg_voice_donation" to false,
        "sg_voice_hide_kb" to false,
        "sg_voice_toolbar" to true,
        "sg_wt_icon_in_strip" to false,
    )
}

object SgItems {
    /** 90 items in the exact web order (SG_ITEMS then help, then about). */
    val ALL: List<SgItem> = listOf(
        SgItem(
            "sg_toolbar",
            "preferences",
            SgType.TOGGLE,
            "Toolbar",
            "टूलबार",
            sumEn = "Show the keyboard toolbar while typing",
            sumHi = "टाइप करते समय कीबोर्ड टूलबार दिखाएं",
            kw = listOf("toolbar", "suggestion strip", "टूलबार"),
            key = "sg_toolbar",
        ),
        SgItem(
            "sg_suggestion_strip",
            "preferences",
            SgType.TOGGLE,
            "Suggestion strip",
            "सुझाव पट्टी",
            sumEn = "Show suggestions and access features",
            sumHi = "सुझाव दिखाएं और सुविधाओं तक पहुंचें",
            kw = listOf("suggestions", "prediction bar", "candidate strip", "hide suggestions"),
            key = "sg_suggestion_strip",
        ),
        SgItem(
            "sg_pin_count",
            "preferences",
            SgType.SLIDER,
            "Icons count on suggestions strip",
            "टूलबार पर आइकॉन की संख्या",
            sumEn = "Define the access point icons count that shown on the suggestion strip. Valid value should between 3 and 8, inclusive",
            sumHi = "सुझाव पट्टी पर दिखने वाले एक्सेस पॉइंट आइकॉन की संख्या तय करें (3–8)",
            kw = listOf("icons count", "access points", "shortcuts"),
            min = 3.0,
            max = 8.0,
            step = 1.0,
            webFn = "() => maxPinnedCapacity() | v => { const n = setPinnedCapacity(v); if(pinnedExtIds.length > n){ pinnedExtIds = pinnedExtIds.slice(0, n); savePinnedIds(pinnedExtIds); } try { renderPinnedRow(); extBuildPages(); } catch(e){} return n; }",
        ),
        SgItem(
            "sg_number_row",
            "preferences",
            SgType.TOGGLE,
            "Number row",
            "नंबर पंक्ति",
            sumEn = "Always show on QWERTY, QWERTZ, and AZERTY layouts",
            sumHi = "QWERTY, QWERTZ और AZERTY लेआउट में हमेशा दिखाएं",
            kw = listOf("number row", "digits", "123", "नंबर"),
            key = "sg_number_row",
        ),
        SgItem(
            "sg_key_borders",
            "preferences",
            SgType.TOGGLE,
            "Key borders",
            "की बॉर्डर",
            kw = listOf("key borders", "outline", "whether to show key borders"),
            key = "sg_key_borders",
        ),
        SgItem(
            "sg_vibrate",
            "preferences",
            SgType.TOGGLE,
            "Vibrate on keypress",
            "कुंजी दबाने पर कंपन (वाइब्रेशन)",
            sumEn = "Haptic feedback — key press par halka vibration",
            sumHi = "की प्रेस पर हल्का कंपन",
            kw = listOf("haptic feedback", "key tap vibration", "haptics", "vibrate"),
            webFn = "() => isHapticEnabled() | v => { try { setHapticEnabled(v); updateHapticToggleUI(); } catch(e){} return v; }",
        ),
        SgItem(
            "sg_sound",
            "preferences",
            SgType.TOGGLE,
            "Sound on keypress",
            "कुंजी दबाने पर आवाज़",
            kw = listOf("sound", "click", "volume", "keypress sound"),
            key = "sg_sound",
        ),
        SgItem(
            "sg_popup",
            "preferences",
            SgType.TOGGLE,
            "Popup on keypress",
            "की पॉप-अप",
            kw = listOf("character popup", "letter preview", "key pop-up", "popup"),
            key = "sg_popup",
        ),
        SgItem(
            "sg_kb_height",
            "preferences",
            SgType.SLIDER,
            "Keyboard height",
            "कीबोर्ड की ऊंचाई",
            sumEn = "A float value to be multiplied when computing keyboard height. The value should between 0.5 and 2.0, inclusive",
            sumHi = "कीबोर्ड की ऊंचाई का अनुपात (0.5 – 2.0)",
            kw = listOf("keyboard height", "ratio", "size", "ऊंचाई"),
            min = 0.5,
            max = 2.0,
            step = 0.05,
            webFn = "() => getKbHeightRatio() | v => setKbHeightRatio(v)",
        ),
        SgItem(
            "sg_double_space_period",
            "preferences",
            SgType.TOGGLE,
            "Double tap on spacebar to add period followed by a space",
            "स्पेस बार दो बार टैप करने पर फुल स्टॉप",
            kw = listOf("double tap period", "spacebar period", "full stop", "period"),
            key = "sg_double_space_period",
        ),
        SgItem(
            "sg_auto_cap",
            "preferences",
            SgType.TOGGLE,
            "Auto-capitalization",
            "अपने-आप कैपिटल लेटर का इस्तेमाल करना",
            sumEn = "Capitalize the first word of each sentence while using on-screen keyboard",
            sumHi = "ऑन-स्क्रीन कीबोर्ड इस्तेमाल करते समय हर वाक्य का पहला शब्द कैपिटल रखें",
            kw = listOf("capitalize words", "sentence case", "auto capitalization"),
            key = "sg_auto_cap",
        ),
        SgItem(
            "sg_show_emoji_key",
            "preferences",
            SgType.TOGGLE,
            "Show a dedicated key to access emoji",
            "इमोजी ऐक्सेस करने के लिए एक समर्पित की दिखाएं",
            sumEn = "Access emoji key with a dedicated key. This hides the language switch key.",
            sumHi = "इमोजी की के लिए अलग कुंजी — इससे भाषा बदलने की कुंजी छिप जाती है.",
            kw = listOf("emoji button", "emoticon key", "emoji key"),
            key = "sg_show_emoji_key",
        ),
        SgItem(
            "sg_show_lang_key",
            "preferences",
            SgType.TOGGLE,
            "Show a dedicated key to switch languages",
            "भाषा बदलने के लिए एक समर्पित कुंजी दिखाएं",
            sumEn = "Change languages with a dedicated key. This hides the emoji key.",
            sumHi = "भाषा बदलने की अलग कुंजी — इससे इमोजी कुंजी छिप जाती है.",
            kw = listOf("language switch key", "globe", "next language"),
            key = "sg_show_lang_key",
        ),
        SgItem(
            "sg_emoji_row",
            "preferences",
            SgType.TOGGLE,
            "Show row of recently used emoji",
            "हाल के इमोजी की पंक्ति दिखाएं",
            kw = listOf("emoji bar", "quick emoji row", "fast access row"),
            key = "sg_emoji_row",
        ),
        SgItem(
            "sg_one_handed",
            "preferences",
            SgType.ACTION,
            "One-handed mode",
            "एक हाथ से इस्तेमाल करने की सुविधा",
            sumEn = "One-handed mode shrinks down your keyboard to let you easily type with one hand",
            sumHi = "कीबोर्ड को छोटा करके एक हाथ से टाइप करने की सुविधा",
            kw = listOf("one handed", "one-handed", "एक हाथ"),
            btn = "left",
            webFn = "() => cycleOneHanded()",
        ),
        SgItem(
            "sg_customize_menus",
            "preferences",
            SgType.ACTION,
            "Customize feature menus",
            "सुविधा के मेन्यू अपनी पसंद के मुताबिक तैयार करें",
            sumEn = "Customize your menu and shortcuts — drag to reorganize, or place in your shortcut top bar",
            sumHi = "मेन्यू और शॉर्टकट सेट करें — खींचकर शॉर्टकट टॉप बार में जोड़ें",
            kw = listOf("customize", "feature menu", "grid", "shortcuts", "drag"),
            btn = "Open",
            webFn = "() => { closeSettings(); try { extOpenPopup(); setTimeout(() => setExtEditMode(true), 120); } catch(e){} }",
        ),
        SgItem(
            "sg_minimize_toolbar",
            "preferences",
            SgType.TOGGLE,
            "Minimize toolbar and hide suggestions",
            "टूलबार को छोटा करें और सुझाव छिपाएं",
            kw = listOf("minimize", "hide suggestions", "toolbar minimize"),
            key = "sg_minimize_toolbar",
        ),
        SgItem(
            "sg_app_list",
            "preferences",
            SgType.GATED,
            "Show in app list",
            "ऐप सूची में दिखाएं",
            sumEn = "App icon, Gboard icon, Hide icon",
            kw = listOf("app icon", "gboard icon", "hide icon", "launcher"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_theme_picker",
            "theme",
            SgType.ACTION,
            "Theme",
            "थीम",
            sumEn = "Dark / Light / AMOLED Black — keyboard ka appearance badlein",
            sumHi = "कीबोर्ड का रूप बदलें",
            kw = listOf("theme", "dark", "light", "amoled", "color", "design"),
            btn = "Change",
            webFn = "() => { closeSettings(); openTheme(); }",
        ),
        SgItem(
            "sg_battery_saver_theme",
            "theme",
            SgType.TOGGLE,
            "Switch to dark theme in battery saver",
            "बैटरी सेवर में डार्क थीम पर जाएं",
            sumEn = "Gboard can save power on OLED screens by going dark",
            sumHi = "OLED स्क्रीन पर Gboard डार्क होकर बैटरी बचा सकता है",
            kw = listOf("battery saver", "oled", "dark theme", "power"),
            key = "sg_battery_saver_theme",
        ),
        SgItem(
            "sg_custom_theme",
            "theme",
            SgType.GATED,
            "Create keyboard theme with my image",
            "अपनी तस्वीर से थीम बनाएं",
            kw = listOf("custom theme", "my image", "photo theme"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_next_lang",
            "languages",
            SgType.ACTION,
            "Next language",
            "अगली भाषा",
            sumEn = "Change keyboards by tapping the new keyboard-switching key (Globe)",
            sumHi = "ग्लोब की दबाकर कीबोर्ड बदलें",
            kw = listOf("language", "globe", "switch input", "add keyboard"),
            btn = "Gondi",
            webFn = "() => { onGlobeTap(); }",
        ),
        SgItem(
            "sg_active_langs",
            "languages",
            SgType.INFO,
            "Active keyboards",
            "सक्रिय कीबोर्ड",
            sumEn = "Masaram Gondi (native) · English (QWERTY) · Hindi → Gondi",
            kw = listOf("languages", "layouts", "active", "enabled languages"),
        ),
        SgItem(
            "sg_multilingual",
            "languages",
            SgType.TOGGLE,
            "Multilingual typing",
            "बहुभाषी टाइपिंग",
            sumEn = "At most %d language(s) can be enabled in multilingual typing",
            sumHi = "बहुभाषी टाइपिंग में अधिकतम भाषाएं चालू की जा सकती हैं",
            kw = listOf("multilingual", "multiple languages", "auto language"),
            key = "sg_multilingual",
        ),
        SgItem(
            "sg_add_keyboard",
            "languages",
            SgType.GATED,
            "Add keyboard",
            "कीबोर्ड जोड़ें",
            kw = listOf("add keyboard", "add language", "layout"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_glide",
            "glide",
            SgType.TOGGLE,
            "Glide typing",
            "ग्लाइड करके टाइप करना",
            sumEn = "Glide your finger from letter to letter",
            sumHi = "अपनी उंगली को एक अक्षर से दूसरे अक्षर पर ग्लाइड करें",
            kw = listOf("glide", "gesture typing", "swipe typing"),
            key = "sg_glide",
        ),
        SgItem(
            "sg_glide_word",
            "glide",
            SgType.TOGGLE,
            "Show the suggested word while gesturing",
            "गेस्चर करते समय सुझाया गया शब्द दिखाएं",
            kw = listOf("glide suggestion", "show word", "gesturing"),
            key = "sg_glide_word",
        ),
        SgItem(
            "sg_glide_trail",
            "glide",
            SgType.TOGGLE,
            "Show how your finger moves across the keyboard",
            "दिखाएं कि उंगली कीबोर्ड पर कैसे चलती है",
            sumEn = "Glide trail",
            sumHi = "ग्लाइड करने का ट्रेल",
            kw = listOf("trail", "glide trail", "show trail"),
            key = "sg_glide_trail",
        ),
        SgItem(
            "sg_glide_cursor",
            "glide",
            SgType.TOGGLE,
            "Cursor control by glide",
            "कर्सर को ग्लाइड करने का कंट्रोल",
            sumEn = "Press & hold the space bar to move the cursor. When disabled, use swipe on space bar for trackpad",
            sumHi = "कर्सर हिलाने के लिए स्पेस बार दबाकर रखें",
            kw = listOf("gesture cursor", "slide spacebar", "move cursor", "trackpad"),
            key = "sg_glide_cursor",
        ),
        SgItem(
            "sg_glide_delete",
            "glide",
            SgType.TOGGLE,
            "Delete swipe",
            "ग्लाइड करके शब्द मिटाने की सुविधा",
            sumEn = "Swipe left from the delete key to erase words",
            sumHi = "मिटाएं कुंजी से बाईं ओर ग्लाइड करके शब्द मिटाएं",
            kw = listOf("gesture delete", "slide delete", "swipe delete"),
            key = "sg_glide_delete",
        ),
        SgItem(
            "sg_auto_correct",
            "correction",
            SgType.TOGGLE,
            "Auto-correction",
            "स्वतः सुधार",
            sumEn = "Correct typos, grammar, and punctuation with just a tap",
            sumHi = "बस टैप करके टाइपो, व्याकरण और विराम चिह्न ठीक करें",
            kw = listOf("autocorrect", "spell correction", "typing correction", "correct words"),
            key = "sg_auto_correct",
        ),
        SgItem(
            "sg_next_word",
            "correction",
            SgType.TOGGLE,
            "Next-word suggestions",
            "अगले शब्द के सुझाव",
            kw = listOf("next word", "predictions", "word suggestions", "predictive text"),
            key = "sg_next_word",
        ),
        SgItem(
            "sg_context",
            "correction",
            SgType.TOGGLE,
            "Use previous context to make suggestions",
            "सुझाव देने के लिए पिछले संदर्भ का इस्तेमाल करें",
            kw = listOf("context", "previous text", "smart suggestions"),
            key = "sg_context",
        ),
        SgItem(
            "sg_inline",
            "correction",
            SgType.TOGGLE,
            "Show typing text inline before selecting candidates",
            "उम्मीदवार चुनने से पहले टेक्स्ट इनलाइन दिखाएं",
            kw = listOf("inline", "composition", "candidates"),
            key = "sg_inline",
        ),
        SgItem(
            "sg_smart_compose",
            "correction",
            SgType.TOGGLE,
            "Smart Compose",
            "स्मार्ट कम्पोज़",
            kw = listOf("smart compose", "sentence completion"),
            key = "sg_smart_compose",
        ),
        SgItem(
            "sg_grammar",
            "correction",
            SgType.TOGGLE,
            "Grammar checker",
            "व्याकरण जांच",
            kw = listOf("grammar", "grammar checker", "punctuation"),
            key = "sg_grammar",
        ),
        SgItem(
            "sg_auto_space",
            "correction",
            SgType.TOGGLE,
            "Automatically add a space after selecting a suggested word",
            "सुझाया गया शब्द चुनने के बाद अपने-आप स्पेस जोड़ें",
            kw = listOf("auto space", "smart punctuation", "spacing"),
            key = "sg_auto_space",
        ),
        SgItem(
            "sg_clear_corrected",
            "correction",
            SgType.ACTION,
            "Clear all corrected words",
            "सभी सुधारे गए शब्द मिटाएं",
            sumEn = "Clear all corrected words?",
            sumHi = "सभी सुधारे गए शब्द मिटाएं?",
            kw = listOf("clear corrected", "reset correction"),
            btn = "Clear",
            webFn = "() => { if(confirm('Clear all corrected words?')){ try { storageSet('mg_corrected_words','[]'); } catch(e){} toast('✓ Clear all corrected words'); } }",
        ),
        SgItem(
            "sg_voice",
            "voice",
            SgType.ACTION,
            "Voice typing",
            "बोली को लिखाई में बदलने की आसान सुविधा",
            sumEn = "Gboard needs access to the microphone in order to enable voice typing.",
            sumHi = "बोली को लिखाई में बदलने के लिए माइक्रोफ़ोन की अनुमति चाहिए.",
            kw = listOf("dictation", "speech to text", "mic button", "voice typing", "assistant voice typing", "nga"),
            btn = "Start",
            webFn = "() => { closeSettings(); try { micStart(); } catch(e){} }",
        ),
        SgItem(
            "sg_voice_auto_start",
            "voice",
            SgType.TOGGLE,
            "Automatically start voice typing when keyboard is shown",
            "कीबोर्ड दिखते ही बोली को लिखाई में बदलना शुरू करें",
            kw = listOf("auto start", "automatically start", "voice toolbar"),
            key = "sg_voice_auto_start",
        ),
        SgItem(
            "sg_voice_auto_punct",
            "voice",
            SgType.TOGGLE,
            "Add punctuation automatically when voice typing",
            "बोलते समय अपने-आप विराम चिह्न जोड़ें",
            kw = listOf("auto punctuation", "punctuation", "voice punctuation", "automatic periods"),
            key = "sg_voice_auto_punct",
        ),
        SgItem(
            "sg_voice_toolbar",
            "voice",
            SgType.TOGGLE,
            "Use the toolbar for easy voice typing",
            "आसान वॉइस टाइपिंग के लिए टूलबार इस्तेमाल करें",
            sumEn = "Hold and drag to move toolbar",
            sumHi = "टूलबार को दबाकर खींचें और हटाएं",
            kw = listOf("voice toolbar", "hold and drag", "toolbar"),
            key = "sg_voice_toolbar",
        ),
        SgItem(
            "sg_voice_hide_kb",
            "voice",
            SgType.TOGGLE,
            "Hide your keyboard while voice typing",
            "बोली को लिखाई में बदलते समय कीबोर्ड को छिपाएं",
            kw = listOf("hide keyboard", "voice typing hide"),
            key = "sg_voice_hide_kb",
        ),
        SgItem(
            "sg_voice_commands",
            "voice",
            SgType.TOGGLE,
            "Show voice commands",
            "आवाज़ के आदेश दिखाएं",
            sumEn = "See voice commands and access settings.",
            sumHi = "आवाज़ के आदेश देखें और सेटिंग ऐक्सेस करें.",
            kw = listOf("voice commands", "all voice commands", "commands list"),
            key = "sg_voice_commands",
        ),
        SgItem(
            "sg_offline_voice",
            "voice",
            SgType.GATED,
            "Offline speech recognition",
            "ऑफ़लाइन स्पीच पहचान",
            sumEn = "Offline mode lets you use voice typing even when there is no internet connection, but you may get slightly different text.",
            kw = listOf("offline mode", "offline dictation", "local speech", "faster voice typing", "100 mb"),
            gate = "Advanced features aren't available in your current Gboard language.",
        ),
        SgItem(
            "sg_enhanced_voice",
            "voice",
            SgType.GATED,
            "Enhanced voice typing",
            "बेहतर वॉइस टाइपिंग",
            sumEn = "Adjust to the language you are speaking if it is supported and detected",
            kw = listOf("assistant voice typing", "nga", "smart dictation", "auto language switching"),
            gate = "Advanced features aren't available in your current Gboard language.",
        ),
        SgItem(
            "sg_emoji_panel",
            "expressions",
            SgType.ACTION,
            "Emoji panel",
            "इमोजी वाला पैनल",
            sumEn = "Open emoji panel",
            sumHi = "इमोजी वाला पैनल खोलें",
            kw = listOf("emoji", "emoticon", "smiley"),
            btn = "Open",
            webFn = "() => { closeSettings(); openEmoji(); }",
        ),
        SgItem(
            "sg_emoji_suggestions",
            "expressions",
            SgType.TOGGLE,
            "Emoji suggestions",
            "इमोजी सुझाव",
            sumEn = "Adds or replaces some words with emoji",
            sumHi = "कुछ शब्दों को इमोजी से जोड़ता या बदलता है",
            kw = listOf("emoji suggestions", "text to emoji", "emojify"),
            key = "sg_emoji_suggestions",
        ),
        SgItem(
            "sg_sticker_suggestions",
            "expressions",
            SgType.TOGGLE,
            "Sticker suggestions",
            "स्टिकर सुझाव",
            kw = listOf("sticker suggestions", "sticker predictions"),
            key = "sg_sticker_suggestions",
        ),
        SgItem(
            "sg_emoji_kitchen",
            "expressions",
            SgType.TOGGLE,
            "Emoji Kitchen",
            "इमोजी किचन",
            sumEn = "Mix emoji, Combine emoji",
            sumHi = "इमोजी मिलाएं / जोड़ें",
            kw = listOf("emoji kitchen", "mix emoji", "combine emoji"),
            key = "sg_emoji_kitchen",
        ),
        SgItem(
            "sg_gif_topics",
            "expressions",
            SgType.GATED,
            "Show topics next to GIF search bar",
            "GIF सर्च बार के पास विषय दिखाएं",
            kw = listOf("gif", "gif topics", "gif search"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_stickers",
            "expressions",
            SgType.GATED,
            "Stickers",
            "स्टिकर",
            kw = listOf("stickers", "bitmoji", "sticker pack", "custom stickers"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_cp_enabled",
            "clipboard",
            SgType.TOGGLE,
            "Clipboard",
            "क्लिपबोर्ड",
            sumEn = "Clipboard allows you to access your recent copy and paste history",
            sumHi = "क्लिपबोर्ड से हाल की कॉपी-पेस्ट हिस्ट्री ऐक्सेस करें",
            kw = listOf("clipboard", "copy paste", "history"),
            key = "sg_cp_enabled",
        ),
        SgItem(
            "sg_cp_suggestions",
            "clipboard",
            SgType.TOGGLE,
            "Show recently copied text and images in suggestions bar",
            "सुझाव बार में हाल में कॉपी किया गया टेक्स्ट और तस्वीरें दिखाएं",
            kw = listOf("copy paste chips", "clipboard suggestions", "paste from clipboard"),
            key = "sg_cp_suggestions",
        ),
        SgItem(
            "sg_cp_retention",
            "clipboard",
            SgType.INFO,
            "Retention",
            "रिटेंशन",
            sumEn = "Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.",
            sumHi = "क्लिप को पिन करने के लिए दबाकर रखें. बिना पिन वाले क्लिप 1 घंटे बाद मिट जाते हैं.",
            kw = listOf("retention", "one hour", "pin", "unpinned"),
        ),
        SgItem(
            "sg_cp_screenshots",
            "clipboard",
            SgType.TOGGLE,
            "Add screenshots to clipboard",
            "स्क्रीनशॉट क्लिपबोर्ड में जोड़ें",
            sumEn = "Add screenshots to your clipboard for easier pasting",
            sumHi = "आसान पेस्टिंग के लिए स्क्रीनशॉट क्लिपबोर्ड में जोड़ें",
            kw = listOf("screenshot", "images", "photo clipboard"),
            key = "sg_cp_screenshots",
        ),
        SgItem(
            "sg_cp_open",
            "clipboard",
            SgType.ACTION,
            "Open clipboard panel",
            "क्लिपबोर्ड पैनल खोलें",
            kw = listOf("clipboard panel", "open clipboard"),
            btn = "Open",
            webFn = "() => { closeSettings(); try { openClipboardPanel(); } catch(e){} }",
        ),
        SgItem(
            "sg_cp_clear",
            "clipboard",
            SgType.ACTION,
            "Clear clipboard history",
            "क्लिपबोर्ड हिस्ट्री मिटाएं",
            sumEn = "Saare saved clips hata dein",
            sumHi = "सभी सहेजे गए क्लिप हटा दें",
            kw = listOf("delete data", "clear history", "reset", "clear clipboard"),
            btn = "Clear",
            webFn = "() => { if(confirm('Saari saved clipboard clips delete kar dein?')){ try { cpSave([]); if(\$('clipboardPanel').classList.contains('open')) cpRenderBody(); } catch(e){} toast('🗑️ Clipboard history clear ho gayi'); } }",
        ),
        SgItem(
            "sg_pd",
            "personalization",
            SgType.ACTION,
            "Personal dictionary",
            "निजी शब्दकोश",
            sumEn = "You don't have any words in the personal dictionary. Tap \"+\" to add a word.",
            sumHi = "आपके निजी शब्दकोश में कोई शब्द नहीं है. शब्द जोड़ने के लिए \"+\" दबाएं.",
            kw = listOf("personal dictionary", "my words", "shortcuts", "dictionary"),
            btn = "Open",
            webFn = "() => { closeSettings(); openPd(); }",
        ),
        SgItem(
            "sg_pd_enabled",
            "personalization",
            SgType.TOGGLE,
            "Use personalized dictionaries",
            "व्यक्तिगत शब्दकोशों का इस्तेमाल करें",
            kw = listOf("personalized dicts", "learned dictionary"),
            key = "sg_pd_enabled",
        ),
        SgItem(
            "sg_learned",
            "personalization",
            SgType.INFO,
            "Learned words",
            "सीखे गए शब्द",
            sumEn = "Improve typing and voice typing based on your usage patterns and corrections",
            sumHi = "आपके उपयोग के पैटर्न और सुधारों के आधार पर टाइपिंग बेहतर होती है",
            kw = listOf("learned words", "personalization", "adapt"),
        ),
        SgItem(
            "sg_conv_history",
            "personalization",
            SgType.TOGGLE,
            "Use conversation history as context",
            "संदर्भ के रूप में बातचीत के इतिहास का इस्तेमाल करें",
            kw = listOf("conversation history", "context", "chat history"),
            key = "sg_conv_history",
        ),
        SgItem(
            "sg_screen_context",
            "personalization",
            SgType.TOGGLE,
            "Use screen context",
            "स्क्रीन संदर्भ का इस्तेमाल करें",
            kw = listOf("screen context", "writing tools context"),
            key = "sg_screen_context",
        ),
        SgItem(
            "sg_adapt",
            "personalization",
            SgType.TOGGLE,
            "Adapt to your typing and voice typing usage patterns",
            "आपके टाइपिंग और वॉइस टाइपिंग पैटर्न के अनुसार ढलें",
            kw = listOf("adapt", "usage patterns", "manage personalization"),
            key = "sg_adapt",
        ),
        SgItem(
            "sg_delete_learned",
            "personalization",
            SgType.ACTION,
            "Delete learned words and data",
            "सीखे गए शब्द और डेटा मिटाएं",
            sumEn = "Your learned words will be erased. This operation cannot be undone. To confirm delete, enter the following number to continue.",
            sumHi = "आपके सीखे गए शब्द मिटा दिए जाएंगे. यह कार्रवाई वापस नहीं ली जा सकती.",
            kw = listOf("delete learned", "clear data", "erase", "reset gboard"),
            btn = "Delete",
            webFn = "() => { const n = 1000 + Math.floor(Math.random()*9000); const a = prompt('Your learned words will be erased. This operation cannot be undone.\\nTo confirm delete, enter this number: ' + n); if(a === null) return; if(String(a).trim() === String(n)){ try { storageSet('mg_learned_words','[]'); stora...",
        ),
        SgItem(
            "sg_incognito",
            "privacy",
            SgType.TOGGLE,
            "Incognito mode",
            "गुप्त मोड",
            sumEn = "Voice typing is disabled in Incognito Mode",
            sumHi = "गुप्त मोड में बोली को लिखाई में बदलने की सुविधा काम नहीं करती",
            kw = listOf("incognito", "private", "गुप्त"),
            key = "sg_incognito",
        ),
        SgItem(
            "sg_stats",
            "privacy",
            SgType.TOGGLE,
            "Automatically send keyboard usage statistics",
            "कीबोर्ड उपयोग के आंकड़े अपने-आप भेजें",
            kw = listOf("usage statistics", "analytics", "improve"),
            key = "sg_stats",
        ),
        SgItem(
            "sg_voice_donation",
            "privacy",
            SgType.TOGGLE,
            "Donate audio to help improve voice typing",
            "वॉइस टाइपिंग बेहतर करने के लिए ऑडियो दान करें",
            sumEn = "If you agree, snippets of your audio input will be sent and stored to help improve voice typing for everyone. Snippets contain a maximum of 15 seconds of speech and can be up to 25 seconds long. They are not kept longer than 18 months.",
            sumHi = "स्वीकार करने पर आपके ऑडियो के छोटे टुकड़े भेजे और सहेजे जाएंगे. अधिकतम 15 सेकंड, 18 महीने से ज़्यादा नहीं रखे जाते.",
            kw = listOf("voice donation", "audio snippets", "donate audio", "18 months"),
            key = "sg_voice_donation",
        ),
        SgItem(
            "sg_privacy_note",
            "privacy",
            SgType.INFO,
            "Profile separation",
            "प्रोफ़ाइल अलगाव",
            sumEn = "Each setting applies to both your personal profile and your work profile, but neither profile can access suggestions, clipboard content, dictionaries or recent emojis associated with the other profile",
            sumHi = "हर सेटिंग व्यक्तिगत और वर्क दोनों प्रोफ़ाइल पर लागू होती है, पर एक प्रोफ़ाइल दूसरी के सुझाव/क्लिपबोर्ड/शब्दकोश ऐक्सेस नहीं कर सकती",
            kw = listOf("work profile", "personal profile", "separation"),
        ),
        SgItem(
            "sg_location",
            "privacy",
            SgType.GATED,
            "Location",
            "स्थान",
            kw = listOf("location", "gps"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_delete_data",
            "privacy",
            SgType.ACTION,
            "Delete data / Reset",
            "डेटा मिटाएं / रीसेट",
            sumEn = "Delete data, Clear history, Reset",
            sumHi = "डेटा मिटाएं, हिस्ट्री साफ़ करें, रीसेट करें",
            kw = listOf("delete data", "clear history", "reset"),
            btn = "Reset",
            webFn = "() => { if(confirm('Clear all on-device data that has been saved to improve your typing experience?')){ try { ['mg_learned_words','mg_corrected_words','mg_personal_dictionary'].forEach(k => storageSet(k,'[]')); } catch(e){} toast('✓ Clear all on-device data'); } }",
        ),
        SgItem(
            "sg_symbols",
            "advanced",
            SgType.ACTION,
            "Symbols keyboard",
            "सिंबल कीबोर्ड",
            sumEn = "Open the on-screen symbols keyboard",
            sumHi = "ऑन-स्क्रीन सिंबल कीबोर्ड खोलें",
            kw = listOf("symbols", "symbols mode", "123", "calculator"),
            btn = "Open",
            webFn = "() => { closeSettings(); extOpenSymbols(); }",
        ),
        SgItem(
            "sg_pk",
            "advanced",
            SgType.GATED,
            "Physical keyboard",
            "फ़िज़िकल कीबोर्ड",
            sumEn = "Access keys and shortcuts without a physical keyboard",
            kw = listOf("physical keyboard", "pk", "bluetooth keyboard", "shortcuts"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_kb_shortcuts",
            "advanced",
            SgType.GATED,
            "Show keyboard shortcuts",
            "कीबोर्ड शॉर्टकट दिखाएं",
            sumEn = "Layouts, keyboard shortcuts and modifier keys",
            kw = listOf("keyboard shortcuts", "modifier keys", "ctrl"),
            gate = "Cannot show keyboard shortcuts in this input field",
        ),
        SgItem(
            "sg_handwriting",
            "advanced",
            SgType.GATED,
            "Handwriting",
            "हस्तलेखन",
            sumEn = "Use your stylus to write in any text field. Your handwriting will be converted to text that you can edit or delete.",
            kw = listOf("handwriting", "stylus", "sign to text"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_morse",
            "advanced",
            SgType.GATED,
            "Morse code",
            "मोर्स कोड",
            sumEn = "Control the Morse keyboard with external switches. The default timeout is 1 second.",
            kw = listOf("morse", "dot key", "dash key", "accessibility"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_display_cutout",
            "advanced",
            SgType.GATED,
            "Display cutout customization",
            "डिस्प्ले कटआउट कस्टमाइज़ेशन",
            sumEn = "Enable this feature if you want to customize the Ignore display cutout area feature.",
            kw = listOf("display cutout", "notch", "ignore cutout"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_text_preview",
            "advanced",
            SgType.TOGGLE,
            "Enable the text preview",
            "टेक्स्ट प्रीव्यू चालू करें",
            kw = listOf("text preview", "preview"),
            key = "sg_text_preview",
        ),
        SgItem(
            "sg_a11y_layout",
            "advanced",
            SgType.GATED,
            "Show accessibility layout",
            "एक्सेसिबिलिटी लेआउट दिखाएं",
            kw = listOf("accessibility", "layout", "large keys"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_floating",
            "advanced",
            SgType.GATED,
            "Floating keyboard",
            "फ़्लोटिंग कीबोर्ड",
            sumEn = "Enable floating keyboard automatically by default when the device is in landscape mode.",
            kw = listOf("floating", "float keyboard", "movable"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_split",
            "advanced",
            SgType.GATED,
            "Split keyboard",
            "स्प्लिट कीबोर्ड",
            sumEn = "When the keyboard is set to split layout, some keys will be duplicated on both sides",
            kw = listOf("split", "tablet", "two sided"),
            gate = "Command not available in this app",
        ),
        SgItem(
            "sg_dbg_order",
            "debug",
            SgType.INFO,
            "Access point icon order",
            "एक्सेस पॉइंट आइकॉन क्रम",
            sumEn = "Define the order of displayed access point icons, separated by semicolon",
            sumHi = "दिखने वाले एक्सेस पॉइंट आइकॉन का क्रम, सेमिकोलन से अलग",
            kw = listOf("access_points_showing_order", "semicolon", "order", "debug"),
            webFn = "() => 'order: ' + (typeof extOrderSemicolon === 'function' ? (extOrderSemicolon() || '(empty)') : '(n/a)')",
        ),
        SgItem(
            "sg_dbg_apply_order",
            "debug",
            SgType.ACTION,
            "Apply order (semicolon)",
            "क्रम लागू करें (सेमिकोलन)",
            sumEn = "e.g. clipboard;emoji;theme;undo;redo",
            kw = listOf("apply order", "semicolon", "import order"),
            btn = "Apply",
            webFn = "() => { const v = prompt('Define the order of displayed access point icons, separated by semicolon', typeof extOrderSemicolon === 'function' ? extOrderSemicolon() : ''); if(v === null) return; if(typeof extApplyOrderSemicolon === 'function' && extApplyOrderSemicolon(v)) toast('✓ Order applied'); ...",
        ),
        SgItem(
            "sg_dbg_capacity",
            "debug",
            SgType.INFO,
            "Icons count on suggestions strip",
            "टूलबार पर आइकॉन संख्या",
            sumEn = "By default, the suggestions strip shows a maximum of 5 (or 6 on landscape mode) access point icons.",
            kw = listOf("capacity", "count", "3 and 8", "debug"),
            webFn = "() => 'capacity: ' + maxPinnedCapacity() + ' · pinned: ' + pinnedExtIds.length",
        ),
        SgItem(
            "sg_dbg_gates",
            "debug",
            SgType.INFO,
            "Gated items",
            "गेटेड आइटम",
            sumEn = "Command not available in this app / Disabled because opt-in is disabled",
            kw = listOf("gated", "disabled", "gate reason"),
            webFn = "() => SG_ITEMS.filter(x => x.type === 'gated').length + ' gated tiles'",
        ),
        SgItem(
            "sg_help_open",
            "help",
            SgType.ACTION,
            "Help & feedback",
            "सहायता और फ़ीडबैक",
            sumEn = "Repositories, features, developer info",
            sumHi = "रिपॉज़िटरी, फ़ीचर, डेवलपर जानकारी",
            kw = listOf("help", "feedback", "support"),
            btn = "Open",
            webFn = "() => { closeSettings(); openInfo(); }",
        ),
        SgItem(
            "sg_help_guide",
            "help",
            SgType.INFO,
            "How to customize the toolbar",
            "टूलबार कैसे कस्टमाइज़ करें",
            sumEn = "Tap the grid icon, then the pencil, then drag items to your shortcut top bar",
            sumHi = "ग्रिड आइकॉन, फिर पेंसिल दबाकर आइटम को शॉर्टकट टॉप बार में खींचें",
            kw = listOf("customize", "drag", "toolbar help"),
        ),
        SgItem(
            "sg_about_open",
            "about",
            SgType.ACTION,
            "About Mgboard_Web",
            "Mgboard_Web के बारे में",
            sumEn = "Masaram Gondi Web Keyboard · repositories · developer",
            sumHi = "मासाराम गोंडी वेब कीबोर्ड",
            kw = listOf("about", "version", "repo"),
            btn = "Open",
            webFn = "() => { closeSettings(); openInfo(); }",
        ),
        SgItem(
            "sg_about_ver",
            "about",
            SgType.INFO,
            "Current version",
            "वर्तमान संस्करण",
            sumEn = "v16.3 · Masaram Gondi Keyboard",
            kw = listOf("version", "current version", "build"),
        ),
        SgItem(
            "sg_about_licenses",
            "about",
            SgType.GATED,
            "Open source licenses",
            "ओपन सोर्स लाइसेंस",
            sumEn = "Zero runtime JavaScript dependencies",
            kw = listOf("licenses", "open source"),
            gate = "Command not available in this app",
        ),
    )

    fun byId(id: String): SgItem? = ALL.firstOrNull { it.id == id }

    fun ofPage(pageId: String): List<SgItem> = ALL.filter { it.page == pageId }

    /**
     * Gboard-exact search: case-insensitive substring over
     * en + hi + sumEn + sumHi + id + keywords (web sgMatches() ka 1:1 port).
     */
    fun matches(it: SgItem, qRaw: String): Boolean {
        val q = qRaw.lowercase()
        if (q.isEmpty()) return false
        val hay = listOfNotNull(it.en, it.hi, it.sumEn, it.sumHi, it.id)
            .plus(it.kw)
            .joinToString(" ")
            .lowercase()
        return hay.contains(q)
    }

    fun search(q: String): List<SgItem> = ALL.filter { matches(it, q) }

    /** Rows whose behaviour needs the MgBoard IME service (not ported yet). */
    val PENDING_IME: Set<String> = setOf(
        "sg_toolbar",
        "sg_pin_count",
        "sg_kb_height",
        "sg_one_handed",
        "sg_customize_menus",
        "sg_theme_picker",
        "sg_next_lang",
        "sg_active_langs",
        "sg_clear_corrected",
        "sg_voice",
        "sg_emoji_panel",
        "sg_cp_open",
        "sg_pd",
        "sg_delete_learned",
        "sg_privacy_note",
        "sg_symbols",
        "sg_dbg_order",
        "sg_dbg_apply_order",
        "sg_help_guide",
        "sg_about_ver",
    )
}
