// GENERATED by scripts/gen_stickers.py — res/raw/stickers_manifest.json se.
// Haath se edit MAT karo; manifest badlo aur script dobara chalao.
package com.mgboard.keyboard.media

/**
 * MgBoard ka apna bundled sticker pack — **zero external dependency**.
 *
 * Gboard ke Stickers tab mein third-party packs aate hain (Bitmoji, sticker.ly);
 * MgBoard apna pack bundle karta hai: offline, koi API key/attribution/rate-limit
 * nahi. Stickers bundled Masaram Gondi font (OFL 1.1) se draw kiye gaye hain
 * (`scripts/stickers` generator), PNG alpha ke saath — `commitContent` pipeline
 * inhe `image/png` MIME se editor ko bhejti hai.
 */
object BundledStickers {
    const val PACK_ID = "mgboard_reactions"
    const val PACK_TITLE = "MgBoard Reactions"
    const val PACK_TITLE_HI = "MgBoard रिएक्शन"
    const val ATTRIBUTION = "MgBoard original sticker pack — Masaram Gondi font (OFL 1.1), drawn in-app"
    const val SIZE = 256

    val ITEMS = listOf(
        BundledSticker(
            id = "sticker_hi", res = "raw/sticker_hi",
            title = "Hi", hi = "नमस्ते",
            tags = listOf("hi", "hello", "namaste", "नमस्ते", "hey", "greet"),
        ),
        BundledSticker(
            id = "sticker_thanks", res = "raw/sticker_thanks",
            title = "Thanks", hi = "धन्यवाद",
            tags = listOf("thanks", "thank you", "dhanyavad", "धन्यवाद", "shukriya"),
        ),
        BundledSticker(
            id = "sticker_wow", res = "raw/sticker_wow",
            title = "Wow", hi = "वाह",
            tags = listOf("wow", "amazing", "वाह", "great", "awesome"),
        ),
        BundledSticker(
            id = "sticker_ok", res = "raw/sticker_ok",
            title = "OK", hi = "ठीक है",
            tags = listOf("ok", "ठीक", "done", "check", "yes ok", "theek"),
        ),
        BundledSticker(
            id = "sticker_yes", res = "raw/sticker_yes",
            title = "Yes", hi = "हाँ",
            tags = listOf("yes", "हाँ", "haan", "thumbs up", "agree", "sure"),
        ),
        BundledSticker(
            id = "sticker_no", res = "raw/sticker_no",
            title = "No", hi = "नहीं",
            tags = listOf("no", "नहीं", "nahi", "cross", "deny", "nope"),
        ),
        BundledSticker(
            id = "sticker_love", res = "raw/sticker_love",
            title = "Love", hi = "प्यार",
            tags = listOf("love", "प्यार", "heart", "pyar", "dil", "like"),
        ),
        BundledSticker(
            id = "sticker_haha", res = "raw/sticker_haha",
            title = "Haha", hi = "हाहा",
            tags = listOf("haha", "laugh", "funny", "हासी", "lol", "मज़ा"),
        ),
        BundledSticker(
            id = "sticker_hmm", res = "raw/sticker_hmm",
            title = "Hmm", hi = "हम्म",
            tags = listOf("hmm", "thinking", "सोच", "हम्म", "confused", "maybe"),
        ),
        BundledSticker(
            id = "sticker_sorry", res = "raw/sticker_sorry",
            title = "Sorry", hi = "माफ़ करें",
            tags = listOf("sorry", "माफ़", "maaf", "apology", "oops"),
        ),
        BundledSticker(
            id = "sticker_morning", res = "raw/sticker_morning",
            title = "Good morning", hi = "सुप्रभात",
            tags = listOf("good morning", "सुप्रभात", "morning", "suprabhat", "hello morning"),
        ),
        BundledSticker(
            id = "sticker_night", res = "raw/sticker_night",
            title = "Good night", hi = "शुभ रात्रि",
            tags = listOf("good night", "शुभ रात्रि", "night", "sleep", "shubh ratri"),
        ),
    )

    /** Tag search — Hindi + English dono tags match hote hain. */
    fun search(q: String): List<BundledSticker> {
        val query = q.trim().lowercase()
        if (query.isEmpty()) return ITEMS
        return ITEMS.filter { st ->
            st.title.lowercase().contains(query) || st.hi.contains(q.trim()) ||
                st.tags.any { it.lowercase().contains(query) }
        }
    }

    fun byId(id: String): BundledSticker? = ITEMS.firstOrNull { it.id == id }
}
