#!/usr/bin/env python3
"""res/raw/stickers_manifest.json → media/BundledStickers.kt generate karta hai.

Single source of truth JSON manifest hai; Kotlin file generate hoti hai taaki
pure-Kotlin tests bina Android resource ke pack verify kar sakein.
Run: python3 scripts/gen_stickers.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'app/src/main/res/raw/stickers_manifest.json')
OUT  = os.path.join(ROOT, 'app/src/main/kotlin/com/mgboard/keyboard/media/BundledStickers.kt')

m = json.load(open(SRC, encoding='utf-8'))
lines = [
    '// GENERATED by scripts/gen_stickers.py — res/raw/stickers_manifest.json se.',
    '// Haath se edit MAT karo; manifest badlo aur script dobara chalao.',
    'package com.mgboard.keyboard.media',
    '',
    '/**',
    ' * MgBoard ka apna bundled sticker pack — **zero external dependency**.',
    ' *',
    ' * Gboard ke Stickers tab mein third-party packs aate hain (Bitmoji, sticker.ly);',
    ' * MgBoard apna pack bundle karta hai: offline, koi API key/attribution/rate-limit',
    ' * nahi. Stickers bundled Masaram Gondi font (OFL 1.1) se draw kiye gaye hain',
    ' * (`scripts/stickers` generator), PNG alpha ke saath — `commitContent` pipeline',
    ' * inhe `image/png` MIME se editor ko bhejti hai.',
    ' */',
    'object BundledStickers {',
    f'    const val PACK_ID = "{m["packs"][0]["id"]}"',
    f'    const val PACK_TITLE = "{m["packs"][0]["title"]}"',
    f'    const val PACK_TITLE_HI = "{m["packs"][0]["hi"]}"',
    f'    const val ATTRIBUTION = "{m["attribution"]}"',
    f'    const val SIZE = {m["size"]}',
    '',
    '    val ITEMS = listOf(',
]
for it in m['packs'][0]['items']:
    tags = ', '.join('"%s"' % t.replace('"', '\\"') for t in it['tags'])
    lines += [
        '        BundledSticker(',
        f'            id = "{it["id"]}", res = "{it["res"]}",',
        f'            title = "{it["title"]}", hi = "{it["hi"]}",',
        f'            tags = listOf({tags}),',
        '        ),',
    ]
lines += [
    '    )',
    '',
    '    /** Tag search — Hindi + English dono tags match hote hain. */',
    '    fun search(q: String): List<BundledSticker> {',
    '        val query = q.trim().lowercase()',
    '        if (query.isEmpty()) return ITEMS',
    '        return ITEMS.filter { st ->',
    '            st.title.lowercase().contains(query) || st.hi.contains(q.trim()) ||',
    '                st.tags.any { it.lowercase().contains(query) }',
    '        }',
    '    }',
    '',
    '    fun byId(id: String): BundledSticker? = ITEMS.firstOrNull { it.id == id }',
    '}',
    '',
]
open(OUT, 'w', encoding='utf-8').write('\n'.join(lines))
print('wrote', OUT, 'with', len(m['packs'][0]['items']), 'stickers')
